/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Definitions.h"
#include "Drivers.h"



int main(void)
{
	gpio_INIT();
	tim_INIT();
	PWM_INIT();
	USART2_INIT();
	TIM2->CCR1 = 0;
	TIM2->CCR2 = 400;
	uint8_t tx_buffer[20] = {0};
	uint8_t rx_buffer[20];
	uint32_t casovnik;
    /* Loop forever */
	while(1)
	{
		  if (button_pushed())
		  {
			  if ((TIM2->CCR1) == 400)
			  {
				  TIM2->CCR1 = 0;
				  TIM2->CCR2 = 400;
			  }else
			  {
				  TIM2->CCR1 += 40;
				  TIM2->CCR2 -= 40;
			  }
			   while (button_pushed()){}
			}


		 usart_receive(rx_buffer, 10);
		 if (strstr(rx_buffer, "TIME__SHOW"))
		 { 		casovnik = TIM3->CNT;
			 	sprintf(tx_buffer, "%d ms\n", casovnik);
			 	usart_transmit(tx_buffer, strlen(tx_buffer));
			 	memset(rx_buffer, 0, sizeof rx_buffer);

		 } else if (strstr(rx_buffer, "TIME_RESET"))
		 {
			 TIM3->CNT = 0;
			 casovnik = TIM3->CNT;
			 sprintf(tx_buffer, "Cas resetiran: %d ms\n", casovnik);
			 usart_transmit(tx_buffer, strlen(tx_buffer));
			 memset(rx_buffer, 0, sizeof rx_buffer);
		 } else
		 {
			 usart_transmit("Neveljaven ukaz", 20);
		 }

		// for (uint32_t a = 0; a < 80000; a++);

	}
}
